### PR TITLE
make some functions inline

### PR DESCRIPTION
**Pull request by nerdralph**
reduces code size when functions are not used

### CODE REVIEW

**Comment by nerdralph** [comment]
I get no build errors with sdcc 3.8.0.  I think the failure is due to Travis using sdcc 3.3.0.

**Comment by cibomahto** [comment]
Makes sense. I'll take a look at updating the CI server to use something more modern. I had it pegged to an old version because they hadn't released a newer binary for Windows, however this is no longer the case: https://sourceforge.net/projects/sdcc/files/sdcc-win64/

**Comment by cibomahto** [comment]
Updating SDCC fixes the first issue, however it looks like an extra example 'play' was checked in, that doesn't have a proper makefile, so the CI test still fails. You can recreate what the test is doing by going to the 'examples' directory and typing 'make' - on Linux, this should build all of the examples cleanly. It doesn't work on Windows because the 'usb_device_cdc_i2c' example compiles some native code; that should probably be fixed but is a separate issue.

**Comment by nerdralph** [comment]
Sorry, I forgot to make a new branch after I created the pull request and before I added the new 'play' subdir.  Or maybe I could've just tagged my fork before generating the pull request instead of going off master.  I'll see what I can do to clean that up.

**Comment by cibomahto** [comment]
No worries, apologies for taking so long to check it out.

**Comment by nerdralph** [comment]
I just pushed the removal of the 'play' example.
I left an update to the Makefile.include to support different flashing
tools.  I'm using:
export WCHISP="ch55xtool.py -r -f"
If you don't set WCHISP, it should work exactly as it did before.

**Comment by nerdralph** [comment]
Any more comments?

**Comment by cibomahto** [comment]
That looks great, thanks!

**Pull request merged**
